# This is

solver_cfg:
  batch_size: 8
  num_of_epochs: 50
  init_lr: 1e-5
  early_stop: "loss_reference"
  early_stop_kwargs: "{'warmup':5,'patience':10}"
  optimizer: 'Adam'
  init_mom: 0.85
  lr_sche: 'ExponentialLR'
  lr_sche_args: 0.98
  lr_sche_kwargs: "{}"
  lr_weights: "{}"
  compile_net: False
  max_step: 0

controller_cfg:
  debug_mode: False
  debug_validation: False
  inference_on_training_set : False
  validate_on_training_set: False
  fold_code: 'B01'
  net_name: 'SCDenseNet'
  matmul_precision: 'high'
  neptune_id: None

data_loader_cfg:
  force_augment: False