# This flag file specify what flags are passed to the guild manager

solver_cfg:
  batch_size: 8
  num_of_epochs: 50
  init_lr: 1e-5
  rAI_fixed_mode: 5
#  optimizer: 'Adam'
#  lr_sche: 'ExponentialLR'
#  lr_sche_args: [0.99]
#  lr_sche_kwargs: "{}"
  optimizer: 'SGD'
  init_mom: 0.85
  lr_sche: 'OneCycleLR'
  lr_sche_args: 0.02
  lr_sche_kwargs: "{'cycle_momentum':True,'three_phase':True,'div_factor':100}"
#  lr_sche: 'CosineAnnealingWarmRestarts'
#  lr_sche_args: '[]'
#  lr_sche_kwargs: "{'T_0': 50, 'T_mult': 2, 'eta_min': 0}"
  compile_net: False
  max_step: 0

controller_cfg:
  debug_mode: False
  debug_validation: False
  inference_on_training_set : False
  validate_on_training_set: False
  fold_code: 'B00'
  net_name: 'rai_old'
  matmul_precision: 'high'

data_loader_cfg:
  force_augment: False
