# This flag file specify what flags are passed to the guild manager

solver_cfg:
  batch_size: 4
  num_of_epochs: 200
  init_lr: 1e-5
  rAI_fixed_mode: 0
  lr_sche: 'ExponentialLR'
  lr_sche_args: [0.99]

controller_cfg:
  debug_mode: False
  debug_validation: False
  inference_on_training_set : False
  validate_on_training_set: False
  fold_code: 'B00'

data_loader_cfg:
  force_augment: False