# For training, patches of [325, 325, 25] is further sampled from the output normalized by this yaml file

ToCanonical:
  {}
Resample:
  - 'input'
RandomMotion:
  translation: 5 # mm
RandomAffine:
  scales: [0.9, 1.1]
  degrees: [0, 0, 15]
RandomFlip:
  - 'lr'
RandomNoise:
  std: [1, 15]
CropOrPad:
  - [350, 350, 30]
  - padding_mode: 0
  - mask_name: "probmap"

