# For inference, all images should have at least 25 slices, otherwise, inference will include empty slices.

ToCanonical:
  {}
Resample:
  - 'input'
#RandomAffine:
#  scales: [0.9, 1.1]
#  degrees: [0, 0, 10]
#RandomFlip:
#  - 'lr'
#RandomNoise:
#  std: [5, 15]
CropOrPad:
  - [224, 224, 16]
  - padding_mode: 0
  - mask_name: "probmap"

